# font_family      CaskaydiaCove Nerd Font Propo
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

#font_family      family="CaskaydiaCove Nerd Font"
font_family         JetBrainsMono Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size 9

disable_ligatures never 

#font_features CaskaydiaCoveNerdFontPropo +ss01 +ss02 +calt +zero
font_features JetBrainsMono-Nerd-Font +calt +zero +ss01 +ss02 

#narrow_symbols   U+E000-U+E00A,U+EA60-U+EBEB 1

spacing 0

cursor_shape beam
cursor_trail 1

window_margin_width 8

confirm_os_window_close 0

#url_style curly
repaint_delay 10
input_delay 3
sync_to_monitor yes

#adjust_line_height  110%

shell fish

map ctrl+c copy_or_interrupt

# BEGIN_KITTY_THEME
include colors.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
#font_family      family="CaskaydiaCove Nerd Font Mono"
#bold_font        auto
#italic_font      auto
#bold_italic_font auto
# END_KITTY_FONTS