# : Manager [[[

[manager]
cwd = { fg = "#f0dfd7" }

# Tab
tab_active = { fg = "#522300", bg = "#ffb68b", bold = true }
tab_inactive = { fg = "#ffdbc8", bg = "#321300" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d2cc5c", bg = "#d2cc5c" }
marker_cut = { fg = "#e8e5ac", bg = "#e8e5ac" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ccc992", bg = "#ccc992" }

# Count
count_copied = { fg = "#1d1d00", bg = "#e8e5ac" }
count_cut = { fg = "#1d1d00", bg = "#e8e5ac" }
count_selected = { fg = "#522300", bg = "#ccc992" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb68b" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#522300", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb68b", fg = "#522300", bold = true }
normal_alt  = { bg = "#52443c", fg = "#d7c2b8" }

# Select mode
select_main = { bg = "#e5bfa9", fg = "#432b1c", bold = true }
select_alt  = { bg = "#52443c", fg = "#d7c2b8" }

# Unset mode
unset_main = { bg = "#ccc992", fg = "#333209", bold = true }
unset_alt  = { bg = "#52443c", fg = "#d7c2b8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb68b", bg = "#413732" }
progress_error = { fg = "#ffb4ab", bg = "#413732" }

# Permissions
permissions_t = { fg = "#bc6939" }
permissions_w = { fg = "#86833f" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#c5bd36" }
permissions_s = { fg = "#ff772f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb68b" }
active = { fg = "#ccc992", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb68b" }
value = { fg = "#f0dfd7" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb68b", bg = "#522300" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb68b" }
title = {}
hovered = { fg = "#e8e5ac", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413732" }
cand = { fg = "#ffb68b" }
rest = { fg = "#522300" }
desc = { fg = "#f0dfd7" }
separator = " ▶ "
separator_style = { fg = "#f0dfd7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dfd7" }
run = { fg = "#f0dfd7" }
footer = { fg = "#432b1c", bg = "#e5bfa9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ccc992" }
title_warn = { fg = "#ffb68b" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dfd7" },
    { name = "*/", fg = "#ffb68b" },
]

# : ]]]