[flavor]
dark = "matugen"
light = "matugen"

# Static overrides on top of the matugen flavor (colors are generated in
# ~/.config/yazi/flavors/matugen.yazi/flavor.toml)

[manager]
border_symbol = "│"

[status]
separator_open = "🭁"
separator_close = "🭠"

[which]
cols = 3

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },
]