# : Manager [[[

[manager]
cwd = { fg = "#e7e0e8" }

# Tab
tab_active = { fg = "#3a255b", bg = "#d5bbfc", bold = true }
tab_inactive = { fg = "#ecdcff", bg = "#240e45" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff738d", bg = "#ff738d" }
marker_cut = { fg = "#ffd9e0", bg = "#ffd9e0" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f1b7c3", bg = "#f1b7c3" }

# Count
count_copied = { fg = "#32101a", bg = "#ffd9e0" }
count_cut = { fg = "#32101a", bg = "#ffd9e0" }
count_selected = { fg = "#3a255b", bg = "#f1b7c3" }

# Border
border_symbol = "│"
border_style  = { fg = "#d5bbfc" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#3a255b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#d5bbfc", fg = "#3a255b", bold = true }
normal_alt  = { bg = "#49454e", fg = "#cbc4cf" }

# Select mode
select_main = { bg = "#cec2db", fg = "#352d40", bold = true }
select_alt  = { bg = "#49454e", fg = "#cbc4cf" }

# Unset mode
unset_main = { bg = "#f1b7c3", fg = "#4b252e", bold = true }
unset_alt  = { bg = "#49454e", fg = "#cbc4cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d5bbfc", bg = "#3b383e" }
progress_error = { fg = "#ffb4ab", bg = "#3b383e" }

# Permissions
permissions_t = { fg = "#8162a2" }
permissions_w = { fg = "#d83758" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff4063" }
permissions_s = { fg = "#9943ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d5bbfc" }
active = { fg = "#f1b7c3", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d5bbfc" }
value = { fg = "#e7e0e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d5bbfc", bg = "#3a255b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d5bbfc" }
title = {}
hovered = { fg = "#ffd9e0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b383e" }
cand = { fg = "#d5bbfc" }
rest = { fg = "#3a255b" }
desc = { fg = "#e7e0e8" }
separator = " ▶ "
separator_style = { fg = "#e7e0e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e7e0e8" }
run = { fg = "#e7e0e8" }
footer = { fg = "#352d40", bg = "#cec2db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f1b7c3" }
title_warn = { fg = "#d5bbfc" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e7e0e8" },
    { name = "*/", fg = "#d5bbfc" },
]

# : ]]]