# : Manager [[[

[manager]
cwd = { fg = "#f0dfd6" }

# Tab
tab_active = { fg = "#4e2600", bg = "#ffb780", bold = true }
tab_inactive = { fg = "#ffdcc4", bg = "#2f1400" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c8cf61", bg = "#c8cf61" }
marker_cut = { fg = "#e3e7af", bg = "#e3e7af" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c6ca95", bg = "#c6ca95" }

# Count
count_copied = { fg = "#1a1d00", bg = "#e3e7af" }
count_cut = { fg = "#1a1d00", bg = "#e3e7af" }
count_selected = { fg = "#4e2600", bg = "#c6ca95" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb780" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#4e2600", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb780", fg = "#4e2600", bold = true }
normal_alt  = { bg = "#51443b", fg = "#d6c3b7" }

# Select mode
select_main = { bg = "#e4bfa7", fg = "#422b1a", bold = true }
select_alt  = { bg = "#51443b", fg = "#d6c3b7" }

# Unset mode
unset_main = { bg = "#c6ca95", fg = "#2f330c", bold = true }
unset_alt  = { bg = "#51443b", fg = "#d6c3b7" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb780", bg = "#413731" }
progress_error = { fg = "#ffb4ab", bg = "#413731" }

# Permissions
permissions_t = { fg = "#b96b39" }
permissions_w = { fg = "#7f8442" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#b9c33a" }
permissions_s = { fg = "#ff812b" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb780" }
active = { fg = "#c6ca95", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb780" }
value = { fg = "#f0dfd6" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb780", bg = "#4e2600" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb780" }
title = {}
hovered = { fg = "#e3e7af", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413731" }
cand = { fg = "#ffb780" }
rest = { fg = "#4e2600" }
desc = { fg = "#f0dfd6" }
separator = " ▶ "
separator_style = { fg = "#f0dfd6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dfd6" }
run = { fg = "#f0dfd6" }
footer = { fg = "#422b1a", bg = "#e4bfa7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c6ca95" }
title_warn = { fg = "#ffb780" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dfd6" },
    { name = "*/", fg = "#ffb780" },
]

# : ]]]