[config]

[templates.hyprland]
input_path = '~/.config/matugen/hyprland.lua.tpl'
output_path = '~/.config/hypr/hypr-g/hyprland/colors.lua'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = '~/.config/matugen/hyprlock.conf.tpl'
output_path = '~/.config/hypr/hypr-g/hyprlock/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/waybar.css.tpl'
output_path = '~/.config/waybar/colors.css'

[templates.yazi]
input_path = '~/.config/matugen/yazi-theme.toml.tpl'
output_path = '~/.config/yazi/theme.toml'

[templates.fuzzel]
input_path = '~/.config/matugen/fuzzel.ini.tpl'
output_path = '~/.config/fuzzel/colors.ini'

[templates.kitty]
input_path = '~/.config/matugen/kitty.conf.tpl'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = '~/.config/matugen/rofi.rasi.tpl'
output_path = '~/.config/rofi/colors.rasi'

[templates.dolphin]
input_path = '~/.config/matugen/dolphin.kvconfig.tpl'
output_path = "~/.config/Kvantum/Matugen/Matugen.kvconfig"

[templates.quickshell]
input_path = '~/.config/matugen/quickshell.qml.tpl'
output_path = '~/.config/quickshell/colors.json'

[templates.vscode]
input_path = "~/.config/matugen/vscode.json.tpl"
output_path = "~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"
# Credits to Lunaris-Project (HyprLuna dot file)