[config]

[templates.hyprland]
input_path = '~/.config/matugen/hyprland.conf.tpl'
output_path = '~/.config/hypr/hypr-g/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/hyprland.conf.tpl'
output_path = '~/.config/hypr/hypr-g/hyprlock/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/waybar.conf.tpl'
output_path = '~/.config/waybar/colors.css'

[templates.yazi]
input_path = '~/.config/matugen/yazi-theme.toml.tpl'
output_path = '~/.config/yazi/theme.toml'