-- Material You color palette (auto-generated by matugen)
-- Colors are defined in a global "colors" table accessible across all required Lua files.
-- Regenerate with: matugen gen -i /path/to/wallpaper

colors = {}

<* for name, value in colors *>
colors.{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>

-- Derived color aliases used in interface.lua / plugin config
colors.border_active    = "rgba({{colors.primary.default.hex_stripped}}d0)"
colors.border_inactive  = "rgba({{colors.on_primary.default.hex_stripped}}ff)"
colors.border_secondary = "rgba({{colors.shadow.default.hex_stripped}}8e)"
colors.shadow_active    = "rgba({{colors.shadow.default.hex_stripped}}4d)"
colors.shadow_inactive  = "rgba({{colors.shadow.default.hex_stripped}}26)"
