/*
 * Waybar color palette template generated by Matugen.
 * Do not edit this file directly, as it will be overwritten.
 */

/* Main colors from the Material You palette */
@define-color primary {{colors.primary.default.hex}};
@define-color on_primary {{colors.on_primary.default.hex}};
@define-color primary_container {{colors.primary_container.default.hex}};
@define-color on_primary_container {{colors.on_primary_container.default.hex}};

@define-color secondary {{colors.secondary.default.hex}};
@define-color on_secondary {{colors.on_secondary.default.hex}};

@define-color tertiary {{colors.tertiary.default.hex}};
@define-color on_tertiary {{colors.on_tertiary.default.hex}};

@define-color background_dark {{colors.surface_dim.default.hex}};
@define-color background_light {{colors.surface_bright.default.hex}};

/* Text and general surface colors */
@define-color foreground {{colors.on_surface.default.hex}};
@define-color background {{colors.surface.default.hex}};
@define-color background_variant {{colors.surface_variant.default.hex}};
@define-color on_background {{colors.on_background.default.hex}};
@define-color container {{colors.surface_container.default.hex}};
@define-color container_high {{colors.surface_container_high.default.hex}};
@define-color container_low {{colors.surface_container_low.default.hex}};

/* Status and feedback colors */
@define-color error {{colors.error.default.hex}};
@define-color on_error {{colors.on_error.default.hex}};
@define-color error_container {{colors.error_container.default.hex}};

/* Accent and decorative colors */
@define-color outline {{colors.outline.default.hex}};
@define-color outline_variant {{colors.outline_variant.default.hex}};
@define-color on_surface_variant {{colors.on_surface_variant.default.hex}};
