/*
 * WebCord custom color template generated by Matugen.
 * Uses the direct .rgb output variable as requested.
 */

:root {
  /* --- BACKGROUNDS --- */
  /* Main chat and message area background */
  --wc-bg-main: {{colors.surface_container_low.default.rgb}};
  /* Server/Channel list background */
  --wc-bg-sidebar: {{colors.surface_container_lowest.default.rgb}};
  /* Header/Title bar background */
  --wc-bg-header: {{colors.surface_container.default.rgb}};
  /* Input/Text area background */
  --wc-bg-input: {{colors.surface_container_high.default.rgb}};
  /* Hover state background */
  --wc-bg-hover: {{colors.surface_container_high.default.rgb}};


  /* --- TEXT/FOREGROUND --- */
  --wc-text-primary: {{colors.on_surface.default.rgb}};
  --wc-text-secondary: {{colors.on_surface_variant.default.rgb}};

  /* --- ACCENTS/PRIMARY --- */
  --wc-accent-primary: {{colors.primary.default.rgb}};
  --wc-accent-secondary: {{colors.secondary.default.rgb}};

  /* --- STATUS/MENTIONS --- */
  --wc-status-online: {{colors.tertiary.default.rgb}};
  --wc-status-error: {{colors.error.default.rgb}};
  /* Transparent primary color for mentions */
  --wc-mention: {{colors.primary_container.default.rgb}};
}