pragma Singleton

import QtQuick
import QtCore
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    //TODO: fix quickshell reload on new color scheme generated by matugen (and quickshell reload that broke the ui sometimes)

    readonly property string homePath: StandardPaths.standardLocations(StandardPaths.HomeLocation)[0].toString().replace(/^file:\/\//, "")
    readonly property string settingsPath: homePath + "/.config/quickshell/settings.json"
    readonly property string templatePath: homePath + "/.config/quickshell/templates/settings.json"

    // Template containing the default settings (tracked in git), read synchronously on demand
    FileView {
        id: templateFile
        path: root.templatePath
        blockLoading: true
        printErrors: false
    }

    FileView {
        id: settingsFile
        path: root.settingsPath
        watchChanges: true
        printErrors: false
        onFileChanged: reload()
        onAdapterUpdated: writeAdapter()

        // settings.json doesn't exist yet: generate it from the template,
        // expanding relative paths with the user's home directory
        onLoadFailed: {
            try {
                const data = JSON.parse(templateFile.text())
                data.wallpapersPath = root.homePath + data.wallpapersPath
                setText(JSON.stringify(data, null, 2))
            } catch (e) {
                console.log("[Settings] Failed to generate settings.json:", e)
            }
        }

        JsonAdapter {
            id: adapter

            property bool isOled: false
            property string fontFamily: "SF Pro Display"
            property string wallpapersPath: root.homePath + "/Pictures/Wallpapers"
        }
    }

    property alias isOled: adapter.isOled
    property alias fontFamily: adapter.fontFamily
    property alias wallpapersPath: adapter.wallpapersPath
}