##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Rule for the main Tor Browser window
windowrule = float on, match:class ^(Tor Browser)$
windowrule = center on, match:class ^(Tor Browser)$

# Rule for the initial Tor Browser Launcher application 
windowrule = float on, match:class ^(Tor Browser Launcher)$
windowrule = center on, match:class ^(Tor Browser Launcher)$