pragma Singleton

import QtQuick
import Quickshell

Singleton {
    id: root

    //TODO: fix quickshell reload on new color scheme generated by matugen (and quickshell reload that broke the ui sometimes)
    readonly property bool isOled: true
    readonly property string fontFamily: "SF Pro Display"
}