pragma Singleton

import QtQuick
import QtCore
import Quickshell

Singleton {
    id: root

    //TODO: fix quickshell reload on new color scheme generated by matugen (and quickshell reload that broke the ui sometimes)
    readonly property bool isOled: false
    readonly property string fontFamily: "SF Pro Display"

    readonly property string wallpapersPath: StandardPaths.standardLocations(StandardPaths.HomeLocation)[0] + "/Pictures/Wallpapers"
}