-- Material You color palette (auto-generated by matugen)
-- Colors are defined in a global "colors" table accessible across all required Lua files.
-- Regenerate with: matugen gen -i /path/to/wallpaper

colors = {}


colors.background = "rgba(191113ff)"

colors.error = "rgba(ffb4abff)"

colors.error_container = "rgba(93000aff)"

colors.inverse_on_surface = "rgba(382e30ff)"

colors.inverse_primary = "rgba(8c4a5eff)"

colors.inverse_surface = "rgba(efdfe1ff)"

colors.on_background = "rgba(efdfe1ff)"

colors.on_error = "rgba(690005ff)"

colors.on_error_container = "rgba(ffdad6ff)"

colors.on_primary = "rgba(551d30ff)"

colors.on_primary_container = "rgba(ffd9e1ff)"

colors.on_primary_fixed = "rgba(3a071bff)"

colors.on_primary_fixed_variant = "rgba(703346ff)"

colors.on_secondary = "rgba(422930ff)"

colors.on_secondary_container = "rgba(ffd9e1ff)"

colors.on_secondary_fixed = "rgba(2b151bff)"

colors.on_secondary_fixed_variant = "rgba(5b3f46ff)"

colors.on_surface = "rgba(efdfe1ff)"

colors.on_surface_variant = "rgba(d6c2c5ff)"

colors.on_tertiary = "rgba(472a0aff)"

colors.on_tertiary_container = "rgba(ffdcc0ff)"

colors.on_tertiary_fixed = "rgba(2d1600ff)"

colors.on_tertiary_fixed_variant = "rgba(613f1fff)"

colors.outline = "rgba(9e8c90ff)"

colors.outline_variant = "rgba(514346ff)"

colors.primary = "rgba(ffb1c5ff)"

colors.primary_container = "rgba(703346ff)"

colors.primary_fixed = "rgba(ffd9e1ff)"

colors.primary_fixed_dim = "rgba(ffb1c5ff)"

colors.scrim = "rgba(000000ff)"

colors.secondary = "rgba(e3bdc5ff)"

colors.secondary_container = "rgba(5b3f46ff)"

colors.secondary_fixed = "rgba(ffd9e1ff)"

colors.secondary_fixed_dim = "rgba(e3bdc5ff)"

colors.shadow = "rgba(000000ff)"

colors.source_color = "rgba(d56589ff)"

colors.surface = "rgba(191113ff)"

colors.surface_bright = "rgba(413739ff)"

colors.surface_container = "rgba(261d1fff)"

colors.surface_container_high = "rgba(31282aff)"

colors.surface_container_highest = "rgba(3c3234ff)"

colors.surface_container_low = "rgba(22191bff)"

colors.surface_container_lowest = "rgba(140c0eff)"

colors.surface_dim = "rgba(191113ff)"

colors.surface_tint = "rgba(ffb1c5ff)"

colors.surface_variant = "rgba(514346ff)"

colors.tertiary = "rgba(eebd93ff)"

colors.tertiary_container = "rgba(613f1fff)"

colors.tertiary_fixed = "rgba(ffdcc0ff)"

colors.tertiary_fixed_dim = "rgba(eebd93ff)"


-- Derived color aliases used in interface.lua / plugin config
colors.border_active    = "rgba(ffb1c5d0)"
colors.border_inactive  = "rgba(551d30ff)"
colors.border_secondary = "rgba(0000008e)"
colors.shadow_active    = "rgba(0000004d)"
colors.shadow_inactive  = "rgba(00000026)"
