# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Persistent workspaces per monitor
# Monitor 1 (eDP-1) - workspaces 1-4
workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true

# Monitor 2 (HDMI-A-1) - workspaces 5-8
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true

# Monitor 3 (DP-1) - workspaces 9-12
workspace = 9, monitor:DP-1, persistent:true
workspace = 10, monitor:DP-1, persistent:true
workspace = 11, monitor:DP-1, persistent:true
workspace = 12, monitor:DP-1, persistent:true

windowrulev2 = idleinhibit, fullscreen, fullscreen:1

layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0
layerrule = match:namespace fuzzel, blur on

# Notification center blur (thanks to zDyant https://github.com/zDyant)
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0
layerrule = match:namespace swaync-notification-window, ignore_alpha 0
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5

layerrule = match:namespace swaync-control-center, animation slide right

# Control Center blur and opacity
layerrule = match:namespace quickshell:controlCenter, blur on
layerrule = match:namespace quickshell:controlCenter, ignore_alpha 0.79
layerrule = match:namespace quickshell:controlCenter, no_anim on

#Top bar animation
#layerrule = match:namespace quickshell:topBar, no_anim on
layerrule = match:namespace quickshell:topBar, animation slide
layerrule_anim = slide, quickshell:topBar, linear, 10

# Notification popup blur and opacity
layerrule = match:namespace quickshell:notificationPopup, blur on
layerrule = match:namespace quickshell:notificationPopup, ignore_alpha 0.79
layerrule = match:namespace quickshell:notificationPopup, animation fade

layerrule = match:namespace selection, no_anim on
layerrule = match:namespace swappy, no_anim on
layerrule = match:namespace hyprshot, no_anim on
layerrule = match:namespace quickshell:notifications, no_anim on