# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Persistent workspaces per monitor
# Monitor 1 (eDP-1) - workspaces 1-4
workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true

# Monitor 2 (HDMI-A-1) - workspaces 5-8
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true

# Monitor 3 (DP-1) - workspaces 9-12
workspace = 9, monitor:DP-1, persistent:true
workspace = 10, monitor:DP-1, persistent:true
workspace = 11, monitor:DP-1, persistent:true
workspace = 12, monitor:DP-1, persistent:true

windowrulev2 = idleinhibit, fullscreen, fullscreen:1

layerrule = blur,waybar
layerrule = ignorezero ,waybar
layerrule = blur,rofi
layerrule = ignorezero ,rofi
layerrule = blur,fuzzel

# Notification center blur (thanks to zDyant https://github.com/zDyant)
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

layerrule = animation slide right, swaync-control-center

# Control Center blur and opacity
layerrule = blur, quickshell:controlCenter
layerrule = ignorealpha 0.79, quickshell:controlCenter
layerrule = noanim, quickshell:controlCenter

#Top bar animation
layerrule = noanim, quickshell:topBar

# Notification popup blur and opacity
layerrule = blur, quickshell:notificationPopup
layerrule = ignorealpha 0.79, quickshell:notificationPopup
layerrule = animation fade, quickshell:notificationPopup